insert into abteilung (AbtNr, AbtName) values (1, 'Hammes and Sons');
insert into abteilung (AbtNr, AbtName) values (2, 'Wolff, Lemke and Price');
insert into abteilung (AbtNr, AbtName) values (3, 'Gibson-Kirlin');
insert into abteilung (AbtNr, AbtName) values (4, 'Nienow LLC');
insert into abteilung (AbtNr, AbtName) values (5, 'Macejkovic, Wiegand and Windler');
insert into abteilung (AbtNr, AbtName) values (6, 'Baumbach and Sons');
insert into abteilung (AbtNr, AbtName) values (7, 'Kertzmann-Veum');
insert into abteilung (AbtNr, AbtName) values (8, 'Champlin-Bogan');
insert into abteilung (AbtNr, AbtName) values (9, 'Auer, Kohler and Steuber');
insert into abteilung (AbtNr, AbtName) values (10, 'Ebert LLC');
insert into abteilung (AbtNr, AbtName) values (11, 'Bernier-Schoen');
insert into abteilung (AbtNr, AbtName) values (12, 'Walsh Inc');
insert into abteilung (AbtNr, AbtName) values (13, 'Gottlieb-Bernhard');
insert into abteilung (AbtNr, AbtName) values (14, 'Murazik, Ortiz and Kuhic');
insert into abteilung (AbtNr, AbtName) values (15, 'Weimann, Luettgen and Purdy');
insert into abteilung (AbtNr, AbtName) values (16, 'Rath Inc');
insert into abteilung (AbtNr, AbtName) values (17, 'Morar and Sons');
insert into abteilung (AbtNr, AbtName) values (18, 'Trantow Inc');
insert into abteilung (AbtNr, AbtName) values (19, 'Douglas, Zemlak and Beer');
insert into abteilung (AbtNr, AbtName) values (20, 'Jacobson-Metz');
insert into abteilung (AbtNr, AbtName) values (21, 'Cruickshank Group');
insert into abteilung (AbtNr, AbtName) values (22, 'Wolf, Blanda and Jacobson');
insert into abteilung (AbtNr, AbtName) values (23, 'Cole, Hartmann and Friesen');
insert into abteilung (AbtNr, AbtName) values (24, 'Jaskolski, Simonis and Spinka');
insert into abteilung (AbtNr, AbtName) values (25, 'Orn Inc');
insert into abteilung (AbtNr, AbtName) values (26, 'Greenfelder-Zieme');
insert into abteilung (AbtNr, AbtName) values (27, 'Rempel-Cummings');
insert into abteilung (AbtNr, AbtName) values (28, 'O''Connell-Keebler');
insert into abteilung (AbtNr, AbtName) values (29, 'Raynor Inc');
insert into abteilung (AbtNr, AbtName) values (30, 'Grimes-Olson');
insert into abteilung (AbtNr, AbtName) values (31, 'Brown, McDermott and Emard');
insert into abteilung (AbtNr, AbtName) values (32, 'Auer-Miller');
insert into abteilung (AbtNr, AbtName) values (33, 'Beatty LLC');
insert into abteilung (AbtNr, AbtName) values (34, 'Kassulke-Medhurst');
insert into abteilung (AbtNr, AbtName) values (35, 'Hauck Group');
insert into abteilung (AbtNr, AbtName) values (36, 'Fay, Torp and Goyette');
insert into abteilung (AbtNr, AbtName) values (37, 'Jones and Sons');
insert into abteilung (AbtNr, AbtName) values (38, 'Feest Inc');
insert into abteilung (AbtNr, AbtName) values (39, 'Grant-Satterfield');
insert into abteilung (AbtNr, AbtName) values (40, 'Johnson, Sauer and Pouros');
insert into abteilung (AbtNr, AbtName) values (41, 'Halvorson Group');
insert into abteilung (AbtNr, AbtName) values (42, 'Little-Smith');
insert into abteilung (AbtNr, AbtName) values (43, 'Spinka and Sons');
insert into abteilung (AbtNr, AbtName) values (44, 'Predovic-O''Conner');
insert into abteilung (AbtNr, AbtName) values (45, 'Swift-Nolan');
insert into abteilung (AbtNr, AbtName) values (46, 'Stamm Inc');
insert into abteilung (AbtNr, AbtName) values (47, 'Hansen, Heathcote and Howell');
insert into abteilung (AbtNr, AbtName) values (48, 'D''Amore, Cummerata and Littel');
insert into abteilung (AbtNr, AbtName) values (49, 'Wolf-Towne');
insert into abteilung (AbtNr, AbtName) values (50, 'Hackett-Brekke');
