insert into hotel (hnr, hname, kategorie, plz, ort) values (1, 'Aivee', 1, 1, 'Xingquan');
insert into hotel (hnr, hname, kategorie, plz, ort) values (2, 'Realpoint', 2, 2, 'Ārān Bīdgol');
insert into hotel (hnr, hname, kategorie, plz, ort) values (3, 'Dabfeed', 3, 3, 'Rengasdengklok');
insert into hotel (hnr, hname, kategorie, plz, ort) values (4, 'Quaxo', 4, 4, 'São Lourenço');
insert into hotel (hnr, hname, kategorie, plz, ort) values (5, 'Jazzy', 5, 5, 'Lhasa');
insert into hotel (hnr, hname, kategorie, plz, ort) values (6, 'Tazzy', 6, 6, 'Sablé-sur-Sarthe');
insert into hotel (hnr, hname, kategorie, plz, ort) values (7, 'Trilith', 7, 7, 'Ibicaraí');
insert into hotel (hnr, hname, kategorie, plz, ort) values (8, 'Jabberbean', 8, 8, 'Fucun');
insert into hotel (hnr, hname, kategorie, plz, ort) values (9, 'Twimm', 9, 9, 'Lokoja');
insert into hotel (hnr, hname, kategorie, plz, ort) values (10, 'Kwilith', 10, 10, 'Tubuhue');
insert into hotel (hnr, hname, kategorie, plz, ort) values (11, 'Rooxo', 11, 11, 'Heka');
insert into hotel (hnr, hname, kategorie, plz, ort) values (12, 'Dabjam', 12, 12, 'Pajeksan');
insert into hotel (hnr, hname, kategorie, plz, ort) values (13, 'Eare', 13, 13, 'Candijay');
insert into hotel (hnr, hname, kategorie, plz, ort) values (14, 'Jabberstorm', 14, 14, 'Shimodate');
insert into hotel (hnr, hname, kategorie, plz, ort) values (15, 'Flashpoint', 15, 15, 'Zumiao');
insert into hotel (hnr, hname, kategorie, plz, ort) values (16, 'Topdrive', 16, 16, 'Staryy Sambor');
insert into hotel (hnr, hname, kategorie, plz, ort) values (17, 'Dabtype', 17, 17, 'Zhenchuan');
insert into hotel (hnr, hname, kategorie, plz, ort) values (18, 'Camido', 18, 18, 'Ciudad Ojeda');
insert into hotel (hnr, hname, kategorie, plz, ort) values (19, 'Avamba', 19, 19, 'Managua');
insert into hotel (hnr, hname, kategorie, plz, ort) values (20, 'Skiba', 20, 20, 'Águas de Lindóia');
insert into hotel (hnr, hname, kategorie, plz, ort) values (21, 'Gevee', 21, 21, 'Campinho');
insert into hotel (hnr, hname, kategorie, plz, ort) values (22, 'Centimia', 22, 22, 'Nocaima');
insert into hotel (hnr, hname, kategorie, plz, ort) values (23, 'Mynte', 23, 23, 'Araci');
insert into hotel (hnr, hname, kategorie, plz, ort) values (24, 'Mydeo', 24, 24, 'Paris 11');
insert into hotel (hnr, hname, kategorie, plz, ort) values (25, 'Blogspan', 25, 25, 'Pedamaran');
insert into hotel (hnr, hname, kategorie, plz, ort) values (26, 'Oyonder', 26, 26, 'Weibin');
insert into hotel (hnr, hname, kategorie, plz, ort) values (27, 'Meejo', 27, 27, 'Dahongmen');
insert into hotel (hnr, hname, kategorie, plz, ort) values (28, 'Ntag', 28, 28, 'Gowa');
insert into hotel (hnr, hname, kategorie, plz, ort) values (29, 'Abatz', 29, 29, 'Ganhe');
insert into hotel (hnr, hname, kategorie, plz, ort) values (30, 'Topicblab', 30, 30, 'Domaradz');
insert into hotel (hnr, hname, kategorie, plz, ort) values (31, 'Linktype', 31, 31, 'Dongfanghong');
insert into hotel (hnr, hname, kategorie, plz, ort) values (32, 'Eabox', 32, 32, 'Huayllati');
insert into hotel (hnr, hname, kategorie, plz, ort) values (33, 'Wikibox', 33, 33, 'Chamalières');
insert into hotel (hnr, hname, kategorie, plz, ort) values (34, 'Gigabox', 34, 34, 'Ylämaa');
insert into hotel (hnr, hname, kategorie, plz, ort) values (35, 'Fivebridge', 35, 35, 'Sundawenang');
insert into hotel (hnr, hname, kategorie, plz, ort) values (36, 'Pixonyx', 36, 36, 'Luoshe');
insert into hotel (hnr, hname, kategorie, plz, ort) values (37, 'Feedspan', 37, 37, 'Outapi');
insert into hotel (hnr, hname, kategorie, plz, ort) values (38, 'Topicshots', 38, 38, 'Pidvolochys’k');
insert into hotel (hnr, hname, kategorie, plz, ort) values (39, 'Linkbuzz', 39, 39, 'Huangbei');
insert into hotel (hnr, hname, kategorie, plz, ort) values (40, 'Fatz', 40, 40, 'San Isidro');
insert into hotel (hnr, hname, kategorie, plz, ort) values (41, 'Eimbee', 41, 41, 'Zambujeira');
insert into hotel (hnr, hname, kategorie, plz, ort) values (42, 'Jayo', 42, 42, 'Vicente Guerrero');
insert into hotel (hnr, hname, kategorie, plz, ort) values (43, 'Centimia', 43, 43, 'Al Faḩāḩīl');
insert into hotel (hnr, hname, kategorie, plz, ort) values (44, 'Jayo', 44, 44, 'Trairi');
insert into hotel (hnr, hname, kategorie, plz, ort) values (45, 'Photobug', 45, 45, 'Miami');
insert into hotel (hnr, hname, kategorie, plz, ort) values (46, 'Innojam', 46, 46, 'Povorino');
insert into hotel (hnr, hname, kategorie, plz, ort) values (47, 'Yacero', 47, 47, 'Jundiaí');
insert into hotel (hnr, hname, kategorie, plz, ort) values (48, 'Gigabox', 48, 48, 'Ganjaran');
insert into hotel (hnr, hname, kategorie, plz, ort) values (49, 'Jayo', 49, 49, 'Maralal');
insert into hotel (hnr, hname, kategorie, plz, ort) values (50, 'Muxo', 50, 50, 'Sumisip');
insert into hotel (hnr, hname, kategorie, plz, ort) values (51, 'Babbleblab', 51, 51, 'Baie-D''Urfé');
insert into hotel (hnr, hname, kategorie, plz, ort) values (52, 'Realblab', 52, 52, 'Lunel');
insert into hotel (hnr, hname, kategorie, plz, ort) values (53, 'Mycat', 53, 53, 'Nowe Miasto nad Pilicą');
insert into hotel (hnr, hname, kategorie, plz, ort) values (54, 'Skippad', 54, 54, 'Marathon');
insert into hotel (hnr, hname, kategorie, plz, ort) values (55, 'Rooxo', 55, 55, 'Brooklyn');
insert into hotel (hnr, hname, kategorie, plz, ort) values (56, 'Topicware', 56, 56, 'Banisilan');
insert into hotel (hnr, hname, kategorie, plz, ort) values (57, 'Flipstorm', 57, 57, 'Azenha');
insert into hotel (hnr, hname, kategorie, plz, ort) values (58, 'DabZ', 58, 58, 'Lubomierz');
insert into hotel (hnr, hname, kategorie, plz, ort) values (59, 'Brainsphere', 59, 59, 'Luchegorsk');
insert into hotel (hnr, hname, kategorie, plz, ort) values (60, 'Meezzy', 60, 60, 'Sumurgayam');
insert into hotel (hnr, hname, kategorie, plz, ort) values (61, 'Wikizz', 61, 61, 'Damai');
insert into hotel (hnr, hname, kategorie, plz, ort) values (62, 'Babbleblab', 62, 62, 'Leicheng');
insert into hotel (hnr, hname, kategorie, plz, ort) values (63, 'Zoomcast', 63, 63, 'Helmsange');
insert into hotel (hnr, hname, kategorie, plz, ort) values (64, 'Gigaclub', 64, 64, 'Bayuin');
insert into hotel (hnr, hname, kategorie, plz, ort) values (65, 'Voomm', 65, 65, 'Rungkang');
insert into hotel (hnr, hname, kategorie, plz, ort) values (66, 'Bubblemix', 66, 66, 'Fengren');
insert into hotel (hnr, hname, kategorie, plz, ort) values (67, 'Podcat', 67, 67, 'Kabo');
insert into hotel (hnr, hname, kategorie, plz, ort) values (68, 'Skippad', 68, 68, 'Eskilstuna');
insert into hotel (hnr, hname, kategorie, plz, ort) values (69, 'Jabbersphere', 69, 69, 'Mandor');
insert into hotel (hnr, hname, kategorie, plz, ort) values (70, 'Centidel', 70, 70, 'Posadas');
insert into hotel (hnr, hname, kategorie, plz, ort) values (71, 'Eabox', 71, 71, 'Keroak');
insert into hotel (hnr, hname, kategorie, plz, ort) values (72, 'Browsetype', 72, 72, 'Kobayashi');
insert into hotel (hnr, hname, kategorie, plz, ort) values (73, 'Katz', 73, 73, 'Smederevo');
insert into hotel (hnr, hname, kategorie, plz, ort) values (74, 'JumpXS', 74, 74, 'Ivanovo-Alekseyevka');
insert into hotel (hnr, hname, kategorie, plz, ort) values (75, 'Trupe', 75, 75, 'Zhangping');
insert into hotel (hnr, hname, kategorie, plz, ort) values (76, 'Yabox', 76, 76, 'Villa Consuelo');
insert into hotel (hnr, hname, kategorie, plz, ort) values (77, 'Agimba', 77, 77, 'Cabimas');
insert into hotel (hnr, hname, kategorie, plz, ort) values (78, 'Trudeo', 78, 78, 'Gori');
insert into hotel (hnr, hname, kategorie, plz, ort) values (79, 'Thoughtbeat', 79, 79, 'Pingtan');
insert into hotel (hnr, hname, kategorie, plz, ort) values (80, 'Camido', 80, 80, 'Taurage');
insert into hotel (hnr, hname, kategorie, plz, ort) values (81, 'Photofeed', 81, 81, 'Itauguá');
insert into hotel (hnr, hname, kategorie, plz, ort) values (82, 'Zoomdog', 82, 82, 'Nancy');
insert into hotel (hnr, hname, kategorie, plz, ort) values (83, 'Roombo', 83, 83, 'Zalaegerszeg');
insert into hotel (hnr, hname, kategorie, plz, ort) values (84, 'Mynte', 84, 84, 'Talipan');
insert into hotel (hnr, hname, kategorie, plz, ort) values (85, 'Geba', 85, 85, 'Danao');
insert into hotel (hnr, hname, kategorie, plz, ort) values (86, 'Riffpath', 86, 86, 'Kitale');
insert into hotel (hnr, hname, kategorie, plz, ort) values (87, 'Flashdog', 87, 87, 'Riachão das Neves');
insert into hotel (hnr, hname, kategorie, plz, ort) values (88, 'Roodel', 88, 88, 'Kout na Šumavě');
insert into hotel (hnr, hname, kategorie, plz, ort) values (89, 'Blognation', 89, 89, 'Minneapolis');
insert into hotel (hnr, hname, kategorie, plz, ort) values (90, 'Trudoo', 90, 90, 'San José Poaquil');
insert into hotel (hnr, hname, kategorie, plz, ort) values (91, 'Zoombeat', 91, 91, 'Prata');
insert into hotel (hnr, hname, kategorie, plz, ort) values (92, 'Brightbean', 92, 92, 'Haolibao');
insert into hotel (hnr, hname, kategorie, plz, ort) values (93, 'Agivu', 93, 93, 'Båstad');
insert into hotel (hnr, hname, kategorie, plz, ort) values (94, 'Flipstorm', 94, 94, 'Cové');
insert into hotel (hnr, hname, kategorie, plz, ort) values (95, 'Skinte', 95, 95, 'El Cantón');
insert into hotel (hnr, hname, kategorie, plz, ort) values (96, 'Mybuzz', 96, 96, 'Phúc Thọ');
insert into hotel (hnr, hname, kategorie, plz, ort) values (97, 'Quaxo', 97, 97, 'Dougou');
insert into hotel (hnr, hname, kategorie, plz, ort) values (98, 'Zoombox', 98, 98, 'Narimanov');
insert into hotel (hnr, hname, kategorie, plz, ort) values (99, 'Feedmix', 99, 99, 'Chugay');
insert into hotel (hnr, hname, kategorie, plz, ort) values (100, 'Oyoba', 100, 100, 'Phalaborwa');
insert into hotel (hnr, hname, kategorie, plz, ort) values (101, 'Realcube', 101, 101, 'Wińsko');
insert into hotel (hnr, hname, kategorie, plz, ort) values (102, 'Fadeo', 102, 102, 'Salaza');
insert into hotel (hnr, hname, kategorie, plz, ort) values (103, 'Skaboo', 103, 103, 'Longxing');
insert into hotel (hnr, hname, kategorie, plz, ort) values (104, 'Avavee', 104, 104, 'Cukanguncal');
insert into hotel (hnr, hname, kategorie, plz, ort) values (105, 'Zoomdog', 105, 105, 'San Miguelito');
insert into hotel (hnr, hname, kategorie, plz, ort) values (106, 'Realfire', 106, 106, 'Weichanglu');
insert into hotel (hnr, hname, kategorie, plz, ort) values (107, 'Blogspan', 107, 107, 'Lirang');
insert into hotel (hnr, hname, kategorie, plz, ort) values (108, 'Rhynoodle', 108, 108, 'Anse Boileau');
insert into hotel (hnr, hname, kategorie, plz, ort) values (109, 'Skiptube', 109, 109, 'Bauta');
insert into hotel (hnr, hname, kategorie, plz, ort) values (110, 'Ailane', 110, 110, 'El Marañón');
insert into hotel (hnr, hname, kategorie, plz, ort) values (111, 'Zoombeat', 111, 111, 'Bianzhuang');
insert into hotel (hnr, hname, kategorie, plz, ort) values (112, 'Chatterbridge', 112, 112, 'Čačak');
insert into hotel (hnr, hname, kategorie, plz, ort) values (113, 'Skilith', 113, 113, 'Thị Trấn Phong Thổ');
insert into hotel (hnr, hname, kategorie, plz, ort) values (114, 'Muxo', 114, 114, 'Akron');
insert into hotel (hnr, hname, kategorie, plz, ort) values (115, 'Voomm', 115, 115, 'Santa Maria da Vitória');
insert into hotel (hnr, hname, kategorie, plz, ort) values (116, 'Kwilith', 116, 116, 'Larnaca');
insert into hotel (hnr, hname, kategorie, plz, ort) values (117, 'Lajo', 117, 117, 'Färgelanda');
insert into hotel (hnr, hname, kategorie, plz, ort) values (118, 'Trupe', 118, 118, 'Shtip');
insert into hotel (hnr, hname, kategorie, plz, ort) values (119, 'Innotype', 119, 119, 'Laliki');
insert into hotel (hnr, hname, kategorie, plz, ort) values (120, 'Topicshots', 120, 120, 'Veinticinco de Mayo');
insert into hotel (hnr, hname, kategorie, plz, ort) values (121, 'Bluejam', 121, 121, 'Baćkowice');
insert into hotel (hnr, hname, kategorie, plz, ort) values (122, 'Rooxo', 122, 122, 'San Juan de Planes');
insert into hotel (hnr, hname, kategorie, plz, ort) values (123, 'Miboo', 123, 123, 'Buraen');
insert into hotel (hnr, hname, kategorie, plz, ort) values (124, 'Bluezoom', 124, 124, 'Veguitas');
insert into hotel (hnr, hname, kategorie, plz, ort) values (125, 'Zoomcast', 125, 125, 'Mongaguá');
insert into hotel (hnr, hname, kategorie, plz, ort) values (126, 'Vidoo', 126, 126, 'Yamrat');
insert into hotel (hnr, hname, kategorie, plz, ort) values (127, 'Plajo', 127, 127, 'Huangyang');
insert into hotel (hnr, hname, kategorie, plz, ort) values (128, 'Twinte', 128, 128, 'Xundian');
insert into hotel (hnr, hname, kategorie, plz, ort) values (129, 'Fadeo', 129, 129, 'Jiuguan');
insert into hotel (hnr, hname, kategorie, plz, ort) values (130, 'Gigaclub', 130, 130, 'Jocotán');
insert into hotel (hnr, hname, kategorie, plz, ort) values (131, 'Meejo', 131, 131, 'Shuigou');
insert into hotel (hnr, hname, kategorie, plz, ort) values (132, 'Gigashots', 132, 132, 'Prachuap Khiri Khan');
insert into hotel (hnr, hname, kategorie, plz, ort) values (133, 'Tagtune', 133, 133, 'Phnom Penh');
insert into hotel (hnr, hname, kategorie, plz, ort) values (134, 'Buzzdog', 134, 134, 'Guankou');
insert into hotel (hnr, hname, kategorie, plz, ort) values (135, 'Wordware', 135, 135, 'Sinacaban');
insert into hotel (hnr, hname, kategorie, plz, ort) values (136, 'Tagcat', 136, 136, 'Tangdong');
insert into hotel (hnr, hname, kategorie, plz, ort) values (137, 'Quire', 137, 137, 'Fale old settlement');
insert into hotel (hnr, hname, kategorie, plz, ort) values (138, 'Zoovu', 138, 138, 'Ambatondrazaka');
insert into hotel (hnr, hname, kategorie, plz, ort) values (139, 'Wikibox', 139, 139, 'Chunmuying');
insert into hotel (hnr, hname, kategorie, plz, ort) values (140, 'Skimia', 140, 140, 'Pil’na');
insert into hotel (hnr, hname, kategorie, plz, ort) values (141, 'Youtags', 141, 141, 'Vila do Bispo');
insert into hotel (hnr, hname, kategorie, plz, ort) values (142, 'Minyx', 142, 142, 'Diriá');
insert into hotel (hnr, hname, kategorie, plz, ort) values (143, 'Blogtag', 143, 143, 'Pyongyang');
insert into hotel (hnr, hname, kategorie, plz, ort) values (144, 'Yakitri', 144, 144, 'Rovnoye');
insert into hotel (hnr, hname, kategorie, plz, ort) values (145, 'Yoveo', 145, 145, 'Carmo do Cajuru');
insert into hotel (hnr, hname, kategorie, plz, ort) values (146, 'Babblestorm', 146, 146, 'Fort Wayne');
insert into hotel (hnr, hname, kategorie, plz, ort) values (147, 'Yata', 147, 147, 'Zubūbah');
insert into hotel (hnr, hname, kategorie, plz, ort) values (148, 'Flipopia', 148, 148, 'Dongsheng');
insert into hotel (hnr, hname, kategorie, plz, ort) values (149, 'Devpoint', 149, 149, 'Teupasenti');
insert into hotel (hnr, hname, kategorie, plz, ort) values (150, 'Reallinks', 150, 150, 'Psychikó');
insert into hotel (hnr, hname, kategorie, plz, ort) values (151, 'Shuffledrive', 151, 151, 'Fengzhou');
insert into hotel (hnr, hname, kategorie, plz, ort) values (152, 'Flashdog', 152, 152, 'Yutan');
insert into hotel (hnr, hname, kategorie, plz, ort) values (153, 'Skyndu', 153, 153, 'Mayumba');
insert into hotel (hnr, hname, kategorie, plz, ort) values (154, 'Linkbridge', 154, 154, 'Saint-Pierre');
insert into hotel (hnr, hname, kategorie, plz, ort) values (155, 'Trunyx', 155, 155, 'Sogod');
insert into hotel (hnr, hname, kategorie, plz, ort) values (156, 'JumpXS', 156, 156, 'Moratuwa');
insert into hotel (hnr, hname, kategorie, plz, ort) values (157, 'Quinu', 157, 157, 'Wenwucao');
insert into hotel (hnr, hname, kategorie, plz, ort) values (158, 'Eabox', 158, 158, 'Roma');
insert into hotel (hnr, hname, kategorie, plz, ort) values (159, 'Midel', 159, 159, 'Denov');
insert into hotel (hnr, hname, kategorie, plz, ort) values (160, 'Dabvine', 160, 160, 'Xomong');
insert into hotel (hnr, hname, kategorie, plz, ort) values (161, 'Skyndu', 161, 161, 'Skotoússa');
insert into hotel (hnr, hname, kategorie, plz, ort) values (162, 'Buzzshare', 162, 162, 'Tintafor');
insert into hotel (hnr, hname, kategorie, plz, ort) values (163, 'Nlounge', 163, 163, 'Vale de Açores');
insert into hotel (hnr, hname, kategorie, plz, ort) values (164, 'Brainbox', 164, 164, 'Zaria');
insert into hotel (hnr, hname, kategorie, plz, ort) values (165, 'Topicstorm', 165, 165, 'Bulan');
insert into hotel (hnr, hname, kategorie, plz, ort) values (166, 'Riffpedia', 166, 166, 'Roissy Charles-de-Gaulle');
insert into hotel (hnr, hname, kategorie, plz, ort) values (167, 'Izio', 167, 167, 'Ábidos');
insert into hotel (hnr, hname, kategorie, plz, ort) values (168, 'Mydeo', 168, 168, 'Masvingo');
insert into hotel (hnr, hname, kategorie, plz, ort) values (169, 'Zoomdog', 169, 169, 'Janaka');
insert into hotel (hnr, hname, kategorie, plz, ort) values (170, 'Devpulse', 170, 170, 'Pedroso');
insert into hotel (hnr, hname, kategorie, plz, ort) values (171, 'Lazz', 171, 171, 'Langgen');
insert into hotel (hnr, hname, kategorie, plz, ort) values (172, 'Realblab', 172, 172, 'Novo');
insert into hotel (hnr, hname, kategorie, plz, ort) values (173, 'Blognation', 173, 173, 'Miraflores');
insert into hotel (hnr, hname, kategorie, plz, ort) values (174, 'Jaxnation', 174, 174, 'Hallsberg');
insert into hotel (hnr, hname, kategorie, plz, ort) values (175, 'JumpXS', 175, 175, 'Vitali');
insert into hotel (hnr, hname, kategorie, plz, ort) values (176, 'Quimm', 176, 176, 'Phitsanulok');
insert into hotel (hnr, hname, kategorie, plz, ort) values (177, 'Mita', 177, 177, 'Malabago');
insert into hotel (hnr, hname, kategorie, plz, ort) values (178, 'Roodel', 178, 178, 'Su-ngai Kolok');
insert into hotel (hnr, hname, kategorie, plz, ort) values (179, 'Layo', 179, 179, 'Dzhiginka');
insert into hotel (hnr, hname, kategorie, plz, ort) values (180, 'Omba', 180, 180, 'Oceanside');
insert into hotel (hnr, hname, kategorie, plz, ort) values (181, 'Centidel', 181, 181, 'Matanzas');
insert into hotel (hnr, hname, kategorie, plz, ort) values (182, 'Zoonder', 182, 182, 'Cavan');
insert into hotel (hnr, hname, kategorie, plz, ort) values (183, 'Flashset', 183, 183, 'Longquan');
insert into hotel (hnr, hname, kategorie, plz, ort) values (184, 'Dabjam', 184, 184, 'Dongfeng');
insert into hotel (hnr, hname, kategorie, plz, ort) values (185, 'Dabtype', 185, 185, 'Boshchorbogh');
insert into hotel (hnr, hname, kategorie, plz, ort) values (186, 'Wikizz', 186, 186, 'Soe');
insert into hotel (hnr, hname, kategorie, plz, ort) values (187, 'Janyx', 187, 187, 'Isnos');
insert into hotel (hnr, hname, kategorie, plz, ort) values (188, 'Gigabox', 188, 188, 'Wanshi');
insert into hotel (hnr, hname, kategorie, plz, ort) values (189, 'Zoomlounge', 189, 189, 'Wudian');
insert into hotel (hnr, hname, kategorie, plz, ort) values (190, 'Jabbersphere', 190, 190, 'Aguaí');
insert into hotel (hnr, hname, kategorie, plz, ort) values (191, 'Einti', 191, 191, 'Qingzhou');
insert into hotel (hnr, hname, kategorie, plz, ort) values (192, 'Divanoodle', 192, 192, 'Al Hufūf');
insert into hotel (hnr, hname, kategorie, plz, ort) values (193, 'Mynte', 193, 193, 'Sortavala');
insert into hotel (hnr, hname, kategorie, plz, ort) values (194, 'Minyx', 194, 194, 'Morangis');
insert into hotel (hnr, hname, kategorie, plz, ort) values (195, 'Aimbu', 195, 195, 'Marsaxlokk');
insert into hotel (hnr, hname, kategorie, plz, ort) values (196, 'Zoovu', 196, 196, 'Capitán Sarmiento');
insert into hotel (hnr, hname, kategorie, plz, ort) values (197, 'Vitz', 197, 197, 'Jiapeng');
insert into hotel (hnr, hname, kategorie, plz, ort) values (198, 'Katz', 198, 198, 'Sanzhou');
insert into hotel (hnr, hname, kategorie, plz, ort) values (199, 'Rhyzio', 199, 199, 'Kalenderovci Donji');
insert into hotel (hnr, hname, kategorie, plz, ort) values (200, 'Meejo', 200, 200, 'Xiongzhang');
