insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (1, 1, 'Programmer Analyst II', 656);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (2, 2, 'Product Engineer', 264);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (3, 3, 'Help Desk Operator', 963);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (4, 4, 'Electrical Engineer', 272);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (5, 5, 'Developer I', 281);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (6, 6, 'Technical Writer', 265);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (7, 7, 'Senior Developer', 199);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (8, 8, 'Marketing Assistant', 318);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (9, 9, 'Financial Analyst', 210);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (10, 10, 'Internal Auditor', 614);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (11, 11, 'Social Worker', 464);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (12, 12, 'Professor', 475);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (13, 13, 'Database Administrator IV', 538);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (14, 14, 'Associate Professor', 680);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (15, 15, 'Software Engineer II', 239);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (16, 16, 'Software Engineer I', 460);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (17, 17, 'Product Engineer', 59);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (18, 18, 'Health Coach I', 127);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (19, 19, 'Data Coordiator', 430);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (20, 20, 'Sales Representative', 516);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (21, 21, 'Account Coordinator', 260);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (22, 22, 'Project Manager', 189);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (23, 23, 'Chemical Engineer', 487);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (24, 24, 'Internal Auditor', 678);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (25, 25, 'Media Manager I', 882);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (26, 26, 'Cost Accountant', 659);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (27, 27, 'Budget/Accounting Analyst II', 884);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (28, 28, 'Developer I', 250);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (29, 29, 'Dental Hygienist', 844);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (30, 30, 'Staff Scientist', 64);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (31, 31, 'Design Engineer', 87);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (32, 32, 'Marketing Manager', 207);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (33, 33, 'Social Worker', 571);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (34, 34, 'Computer Systems Analyst I', 155);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (35, 35, 'Financial Advisor', 324);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (36, 36, 'Operator', 460);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (37, 37, 'Junior Executive', 166);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (38, 38, 'Human Resources Manager', 599);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (39, 39, 'Recruiter', 261);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (40, 40, 'Senior Cost Accountant', 211);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (41, 41, 'Financial Analyst', 696);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (42, 42, 'Librarian', 565);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (43, 43, 'Clinical Specialist', 16);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (44, 44, 'Editor', 491);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (45, 45, 'Human Resources Assistant II', 32);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (46, 46, 'Graphic Designer', 716);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (47, 47, 'Dental Hygienist', 942);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (48, 48, 'VP Marketing', 878);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (49, 49, 'Associate Professor', 609);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (50, 50, 'VP Sales', 568);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (51, 51, 'Food Chemist', 807);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (52, 52, 'Health Coach I', 158);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (53, 53, 'Account Executive', 850);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (54, 54, 'Senior Developer', 393);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (55, 55, 'Account Executive', 502);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (56, 56, 'Software Test Engineer IV', 131);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (57, 57, 'Accounting Assistant I', 827);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (58, 58, 'Programmer Analyst III', 513);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (59, 59, 'Compensation Analyst', 527);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (60, 60, 'Librarian', 848);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (61, 61, 'Director of Sales', 561);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (62, 62, 'Executive Secretary', 157);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (63, 63, 'VP Product Management', 385);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (64, 64, 'Sales Representative', 568);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (65, 65, 'Programmer IV', 332);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (66, 66, 'Software Engineer I', 7);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (67, 67, 'Budget/Accounting Analyst I', 280);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (68, 68, 'Nurse', 543);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (69, 69, 'Research Associate', 338);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (70, 70, 'Budget/Accounting Analyst IV', 821);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (71, 71, 'Automation Specialist I', 269);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (72, 72, 'Tax Accountant', 259);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (73, 73, 'General Manager', 332);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (74, 74, 'Clinical Specialist', 944);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (75, 75, 'Dental Hygienist', 941);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (76, 76, 'Chemical Engineer', 483);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (77, 77, 'Nurse', 49);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (78, 78, 'Data Coordiator', 160);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (79, 79, 'Automation Specialist I', 963);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (80, 80, 'Tax Accountant', 905);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (81, 81, 'Dental Hygienist', 806);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (82, 82, 'Pharmacist', 341);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (83, 83, 'Food Chemist', 247);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (84, 84, 'Recruiting Manager', 190);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (85, 85, 'Web Developer II', 955);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (86, 86, 'Media Manager III', 354);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (87, 87, 'Project Manager', 688);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (88, 88, 'Office Assistant III', 384);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (89, 89, 'Software Engineer II', 821);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (90, 90, 'Director of Sales', 366);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (91, 91, 'Legal Assistant', 117);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (92, 92, 'Structural Engineer', 333);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (93, 93, 'Product Engineer', 706);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (94, 94, 'Staff Scientist', 98);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (95, 95, 'Teacher', 315);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (96, 96, 'Legal Assistant', 973);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (97, 97, 'Legal Assistant', 646);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (98, 98, 'Sales Representative', 998);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (99, 99, 'Director of Sales', 275);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (100, 100, 'Recruiting Manager', 280);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (101, 101, 'Software Engineer III', 714);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (102, 102, 'Structural Engineer', 230);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (103, 103, 'Environmental Tech', 616);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (104, 104, 'Media Manager III', 876);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (105, 105, 'Senior Editor', 548);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (106, 106, 'Electrical Engineer', 357);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (107, 107, 'GIS Technical Architect', 901);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (108, 108, 'Associate Professor', 154);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (109, 109, 'Software Engineer II', 87);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (110, 110, 'Financial Analyst', 91);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (111, 111, 'Financial Analyst', 819);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (112, 112, 'Assistant Professor', 962);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (113, 113, 'Assistant Media Planner', 911);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (114, 114, 'Electrical Engineer', 801);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (115, 115, 'Safety Technician I', 573);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (116, 116, 'Assistant Professor', 761);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (117, 117, 'Account Executive', 914);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (118, 118, 'Computer Systems Analyst II', 978);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (119, 119, 'Librarian', 993);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (120, 120, 'Chemical Engineer', 496);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (121, 121, 'Environmental Specialist', 825);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (122, 122, 'Project Manager', 748);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (123, 123, 'Senior Developer', 866);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (124, 124, 'Analog Circuit Design manager', 999);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (125, 125, 'Senior Financial Analyst', 725);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (126, 126, 'Senior Editor', 563);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (127, 127, 'General Manager', 899);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (128, 128, 'Analog Circuit Design manager', 150);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (129, 129, 'Dental Hygienist', 518);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (130, 130, 'Compensation Analyst', 65);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (131, 131, 'Registered Nurse', 27);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (132, 132, 'Legal Assistant', 822);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (133, 133, 'Account Executive', 424);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (134, 134, 'Pharmacist', 981);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (135, 135, 'Business Systems Development Analyst', 850);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (136, 136, 'Human Resources Assistant III', 71);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (137, 137, 'Automation Specialist IV', 804);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (138, 138, 'Sales Representative', 65);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (139, 139, 'Web Developer III', 687);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (140, 140, 'Financial Analyst', 568);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (141, 141, 'Budget/Accounting Analyst IV', 7);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (142, 142, 'Operator', 349);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (143, 143, 'Statistician III', 421);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (144, 144, 'Senior Sales Associate', 425);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (145, 145, 'Structural Engineer', 10);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (146, 146, 'Occupational Therapist', 72);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (147, 147, 'Senior Editor', 362);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (148, 148, 'Safety Technician II', 915);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (149, 149, 'Registered Nurse', 362);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (150, 150, 'Quality Control Specialist', 492);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (151, 151, 'Information Systems Manager', 693);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (152, 152, 'Editor', 156);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (153, 153, 'Payment Adjustment Coordinator', 927);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (154, 154, 'Account Coordinator', 626);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (155, 155, 'Programmer Analyst II', 431);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (156, 156, 'Senior Editor', 503);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (157, 157, 'Marketing Assistant', 348);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (158, 158, 'Librarian', 665);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (159, 159, 'Research Assistant III', 635);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (160, 160, 'Financial Advisor', 957);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (161, 161, 'Quality Engineer', 764);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (162, 162, 'Actuary', 813);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (163, 163, 'Marketing Assistant', 166);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (164, 164, 'Senior Financial Analyst', 590);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (165, 165, 'Software Test Engineer I', 692);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (166, 166, 'GIS Technical Architect', 465);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (167, 167, 'Financial Advisor', 650);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (168, 168, 'Sales Representative', 429);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (169, 169, 'Accounting Assistant I', 784);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (170, 170, 'Nuclear Power Engineer', 566);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (171, 171, 'Director of Sales', 120);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (172, 172, 'Physical Therapy Assistant', 935);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (173, 173, 'Staff Scientist', 600);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (174, 174, 'Structural Analysis Engineer', 134);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (175, 175, 'Senior Developer', 103);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (176, 176, 'Senior Editor', 788);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (177, 177, 'Geological Engineer', 137);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (178, 178, 'VP Accounting', 40);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (179, 179, 'Analyst Programmer', 406);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (180, 180, 'Marketing Assistant', 238);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (181, 181, 'Junior Executive', 581);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (182, 182, 'Engineer II', 918);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (183, 183, 'Assistant Manager', 86);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (184, 184, 'Administrative Assistant III', 656);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (185, 185, 'VP Accounting', 188);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (186, 186, 'Cost Accountant', 312);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (187, 187, 'Quality Engineer', 452);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (188, 188, 'Executive Secretary', 65);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (189, 189, 'Accounting Assistant I', 454);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (190, 190, 'Technical Writer', 670);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (191, 191, 'Speech Pathologist', 461);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (192, 192, 'Associate Professor', 552);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (193, 193, 'General Manager', 970);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (194, 194, 'Staff Accountant I', 672);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (195, 195, 'Senior Cost Accountant', 999);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (196, 196, 'Community Outreach Specialist', 329);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (197, 197, 'Financial Advisor', 707);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (198, 198, 'Physical Therapy Assistant', 395);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (199, 199, 'Technical Writer', 884);
insert into projektmitarbeit (pnr, projektnr, taetigkeit, stunden) values (200, 200, 'Chemical Engineer', 754);
