insert into buerger (bid, name, age, gender, strasse, plz, ort) values (1, 'Wes', 29, 'binary', 'Fairview', '2240', 'Rushankou');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (2, 'Minette', 97, 'diverse', 'Marquette', '7', 'Ivatsevichy');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (3, 'Aileen', 37, 'diverse', 'Corscot', '32639', 'Mulyosari');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (4, 'Henrik', 38, 'female', 'Del Mar', '722', 'Huangxikou');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (5, 'Astrid', 64, 'male', 'Kropf', '204', 'Baishuiyang');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (6, 'Leroy', 38, 'female', 'Texas', '19', 'Pop');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (7, 'Lauraine', 32, 'female', 'Sutteridge', '2', 'Sarajevo');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (8, 'Cathleen', 42, 'male', 'Ridgeway', '8543', 'Shibukawa');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (9, 'Duff', 33, 'diverse', 'Hallows', '59', 'Araçatuba');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (10, 'Kai', 99, 'nonbinary', 'Rusk', '54', 'Tržič');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (11, 'Kirk', 94, 'male', 'Carey', '44834', 'Dengtang');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (12, 'Nevin', 70, 'diverse', 'Weeping Birch', '587', 'Zinat');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (13, 'Costa', 12, 'binary', 'Cherokee', '2473', 'Kabir');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (14, 'Anna-diana', 5, 'diverse', 'Dexter', '968', 'Birnin Kebbi');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (15, 'Cecilio', 98, 'female', 'Buell', '88', 'Évosmos');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (16, 'Stepha', 41, 'nonbinary', 'Summer Ridge', '99', 'Qincheng');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (17, 'Othilie', 94, 'nonbinary', 'Morningstar', '6226', 'Shingū');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (18, 'Free', 30, 'male', 'Talisman', '79', 'Gataivai');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (19, 'Byrann', 94, 'female', 'Westend', '639', 'Huanipaca');
insert into buerger (bid, name, age, gender, strasse, plz, ort) values (20, 'Neill', 32, 'binary', 'Goodland', '5', 'Cochrane');
