insert into gesundheitsamt (amtid, strasse, plz, ort) values (1, 'Esker', '435', 'Antaparco');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (2, 'Mifflin', '3136', 'Lapaz');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (3, 'Memorial', '26028', 'Marumori');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (4, 'Esker', '76', 'Sinŭiju');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (5, 'Village', '06', 'Bitin');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (6, 'Park Meadow', '8', 'Sarreguemines');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (7, 'Duke', '215', 'Dadong');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (8, 'Merrick', '7', 'Zbarazh');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (9, 'Stang', '0', 'Bayt Ūmmar');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (10, 'Cambridge', '0414', 'Al Jahrā’');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (11, 'Annamark', '70', 'Krajan Kidul Rojopolo');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (12, 'Cody', '1', 'Czudec');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (13, 'Mayfield', '901', 'Veselynove');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (14, 'Crest Line', '10671', 'Dadukou');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (15, 'Alpine', '9943', 'Aplahoué');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (16, 'Bultman', '91689', 'Cauto Cristo');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (17, 'Lakeland', '8', 'Gembu');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (18, 'Calypso', '8444', 'Yako');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (19, 'Westerfield', '39', 'Hénin-Beaumont');
insert into gesundheitsamt (amtid, strasse, plz, ort) values (20, 'Coleman', '07042', 'Taurisma');
