insert into impfzentrum (izid, strasse, plz, ort) values (1, 'Stone Corner', '0616', 'Manaus');
insert into impfzentrum (izid, strasse, plz, ort) values (2, 'Grasskamp', '42100', 'Dayapan');
insert into impfzentrum (izid, strasse, plz, ort) values (3, 'Buell', '4', 'Lianzhou');
insert into impfzentrum (izid, strasse, plz, ort) values (4, 'Redwing', '59', 'Richmond');
insert into impfzentrum (izid, strasse, plz, ort) values (5, 'Huxley', '4', 'Malandag');
insert into impfzentrum (izid, strasse, plz, ort) values (6, 'Roth', '7482', 'Jinbi');
insert into impfzentrum (izid, strasse, plz, ort) values (7, 'Katie', '389', 'Lysekil');
insert into impfzentrum (izid, strasse, plz, ort) values (8, 'Grasskamp', '3', 'Ningxi');
insert into impfzentrum (izid, strasse, plz, ort) values (9, 'Jenna', '8', 'Mali Iđoš');
insert into impfzentrum (izid, strasse, plz, ort) values (10, 'Ryan', '911', 'Votorantim');
insert into impfzentrum (izid, strasse, plz, ort) values (11, 'Gale', '3', 'Mwinilunga');
insert into impfzentrum (izid, strasse, plz, ort) values (12, 'Tomscot', '53503', 'Xinyu');
insert into impfzentrum (izid, strasse, plz, ort) values (13, 'Vermont', '46879', 'Garoua Boulaï');
insert into impfzentrum (izid, strasse, plz, ort) values (14, 'Hoard', '340', 'Strabychovo');
insert into impfzentrum (izid, strasse, plz, ort) values (15, 'Mockingbird', '04', 'Lasehao');
insert into impfzentrum (izid, strasse, plz, ort) values (16, 'Merchant', '10', 'Sanlicheng');
insert into impfzentrum (izid, strasse, plz, ort) values (17, 'Kropf', '71039', 'Lyon');
insert into impfzentrum (izid, strasse, plz, ort) values (18, 'Bowman', '7812', 'Ami');
insert into impfzentrum (izid, strasse, plz, ort) values (19, 'Del Mar', '30', 'Doumuhu');
insert into impfzentrum (izid, strasse, plz, ort) values (20, 'Talisman', '3209', 'Talisay');
