insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (1, 'Support', 'Erie', '4951', 'Rudnya');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (2, 'Training', 'Surrey', '433', 'Hilotongan');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (3, 'Research and Development', 'Talmadge', '200', 'Tögrög');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (4, 'Services', 'Comanche', '384', 'Xinmin');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (5, 'Accounting', 'Rigney', '41834', 'Pancoran');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (6, 'Business Development', 'Maryland', '067', 'Tianyi');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (7, 'Research and Development', 'Bay', '7', 'Beishan');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (8, 'Research and Development', 'Buena Vista', '869', 'Cimongkor');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (9, 'Product Management', 'Golf View', '0444', 'Lâm Thao');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (10, 'Services', 'Shoshone', '52503', 'Igir-igir');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (11, 'Training', 'Nelson', '062', 'Panggungsari');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (12, 'Services', 'Montana', '36', 'Quinarayan');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (13, 'Legal', 'Hollow Ridge', '208', 'Cové');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (14, 'Sales', '6th', '4836', 'Shibata');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (15, 'Research and Development', 'Marcy', '53', 'Saint John');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (16, 'Marketing', 'Amoth', '069', 'Urho');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (17, 'Accounting', '7th', '10700', 'Povenets');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (18, 'Services', 'Holy Cross', '934', 'Marxog');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (19, 'Human Resources', '8th', '64', 'Alvaiázere');
insert into mitarbeiter (mid, berufstaetigkeit, strasse, plz, ort) values (20, 'Human Resources', 'Muir', '5464', 'Longotea');
