insert into testzentrum (tzid, strasse, plz, ort) values (1, 'Bonner', '3', 'Trzebinia');
insert into testzentrum (tzid, strasse, plz, ort) values (2, 'Jenna', '954', 'Xiadian');
insert into testzentrum (tzid, strasse, plz, ort) values (3, 'Walton', '80', 'Drakino');
insert into testzentrum (tzid, strasse, plz, ort) values (4, 'School', '58', 'Washington');
insert into testzentrum (tzid, strasse, plz, ort) values (5, 'Londonderry', '5073', 'Alajuelita');
insert into testzentrum (tzid, strasse, plz, ort) values (6, 'Lerdahl', '47372', 'Ubon Ratchathani');
insert into testzentrum (tzid, strasse, plz, ort) values (7, '5th', '99919', 'Qingxi');
insert into testzentrum (tzid, strasse, plz, ort) values (8, 'Coolidge', '51161', 'Al Jamālīyah');
insert into testzentrum (tzid, strasse, plz, ort) values (9, 'Bowman', '66565', 'Nantes');
insert into testzentrum (tzid, strasse, plz, ort) values (10, 'Rieder', '0964', 'Sölvesborg');
insert into testzentrum (tzid, strasse, plz, ort) values (11, 'Oak Valley', '017', 'Sangke');
insert into testzentrum (tzid, strasse, plz, ort) values (12, 'Mcbride', '0559', 'Sâmraông');
insert into testzentrum (tzid, strasse, plz, ort) values (13, 'Stuart', '774', 'Rio Claro');
insert into testzentrum (tzid, strasse, plz, ort) values (14, 'Kipling', '7822', 'Mizque');
insert into testzentrum (tzid, strasse, plz, ort) values (15, 'Darwin', '9', 'Gongnong');
insert into testzentrum (tzid, strasse, plz, ort) values (16, 'Russell', '9', 'Vyshneve');
insert into testzentrum (tzid, strasse, plz, ort) values (17, 'Delladonna', '1152', 'Xinhua');
insert into testzentrum (tzid, strasse, plz, ort) values (18, 'Dwight', '54', 'Smiřice');
insert into testzentrum (tzid, strasse, plz, ort) values (19, 'Karstens', '5', 'Monjas');
insert into testzentrum (tzid, strasse, plz, ort) values (20, 'Burrows', '82', 'Jiangdong');
